from django.urls import path

from .web_views import (
    admin_dashboard,
    admin_departments,
    admin_department_detail,
    admin_payroll,
    admin_reports,
    admin_reports_export,
    admin_settings,
    admin_settings_history,
    admin_settings_update,
    admin_system,
    admin_system_backup_create,
    admin_system_backup_download,
    admin_system_backup_restore,
    admin_system_logs_export,
    admin_system_monitoring,
    admin_users,
    admin_user_detail,
    profile_view,
    employee_availability,
    employee_availability_update,
    employee_shift_request_create,
    employee_dashboard,
    employee_notifications,
    employee_payroll,
    employee_schedule,
    employee_tasks,
    logout_view,
    manager_calendar,
    manager_dashboard,
    manager_employees,
    manager_payroll,
    manager_requests,
    manager_tasks,
    manager_chat,
    manager_employee_detail,
)

urlpatterns = [
    path('logout/', logout_view, name='logout'),
    path('dashboard/admin/', admin_dashboard, name='admin-dashboard'),
    path('dashboard/admin/users/', admin_users, name='admin-users'),
    path('dashboard/admin/users/<int:user_id>/', admin_user_detail, name='admin-user-detail'),
    path('dashboard/admin/departments/', admin_departments, name='admin-departments'),
    path('dashboard/admin/departments/<int:department_id>/', admin_department_detail, name='admin-department-detail'),
    path('dashboard/admin/settings/', admin_settings, name='admin-settings'),
    path('dashboard/admin/settings/history/', admin_settings_history, name='admin-settings-history'),
    path('dashboard/admin/settings/update/', admin_settings_update, name='admin-settings-update'),
    path('dashboard/admin/reports/', admin_reports, name='admin-reports'),
    path('dashboard/admin/reports/export/', admin_reports_export, name='admin-reports-export'),
    path('dashboard/admin/payroll/', admin_payroll, name='admin-payroll'),
    path('dashboard/admin/system/', admin_system, name='admin-system'),
    path('dashboard/admin/system/backups/create/', admin_system_backup_create, name='admin-system-backup-create'),
    path('dashboard/admin/system/backups/<int:backup_id>/download/', admin_system_backup_download, name='admin-system-backup-download'),
    path('dashboard/admin/system/backups/<int:backup_id>/restore/', admin_system_backup_restore, name='admin-system-backup-restore'),
    path('dashboard/admin/system/logs/export/', admin_system_logs_export, name='admin-system-logs-export'),
    path('dashboard/admin/system/monitoring/', admin_system_monitoring, name='admin-system-monitoring'),
    path('dashboard/profile/', profile_view, name='profile'),
    path('dashboard/manager/', manager_dashboard, name='manager-dashboard'),
    path('dashboard/manager/calendar/', manager_calendar, name='manager-calendar'),
    path('dashboard/manager/requests/', manager_requests, name='manager-requests'),
    path('dashboard/manager/tasks/', manager_tasks, name='manager-tasks'),
    path('dashboard/manager/payroll/', manager_payroll, name='manager-payroll'),
    path('dashboard/manager/employees/', manager_employees, name='manager-employees'),
    path('dashboard/manager/employees/<int:user_id>/', manager_employee_detail, name='manager-employee-detail'),
    path('dashboard/manager/chat/', manager_chat, name='manager-chat'),
    path('dashboard/employee/', employee_dashboard, name='employee-dashboard'),
    path('dashboard/employee/schedule/', employee_schedule, name='employee-schedule'),
    path('dashboard/employee/availability/', employee_availability, name='employee-availability'),
    path('dashboard/employee/availability/update/', employee_availability_update, name='employee-availability-update'),
    path('dashboard/employee/availability/requests/', employee_shift_request_create, name='employee-shift-request-create'),
    path('dashboard/employee/tasks/', employee_tasks, name='employee-tasks'),
    path('dashboard/employee/payroll/', employee_payroll, name='employee-payroll'),
    path('dashboard/employee/notifications/', employee_notifications, name='employee-notifications'),
]
