from django.urls import path

from .admin_api import (
    AdminSettingsHistoryView,
    AdminSettingsView,
    AdminSystemBackupCreateView,
    AdminSystemBackupRestoreView,
    AdminSystemMonitoringView,
)
from .views import (
    ApiRootView,
    DepartmentArchiveView,
    DepartmentDetailView,
    DepartmentListView,
    EmployeeDetailView,
    EmployeeAvatarView,
    EmployeeActivateView,
    EmployeeDeactivateView,
    EmployeeImportView,
    EmployeeListCreateView,
    EmployeeAbsenceView,
    LoginView,
    LogoutView,
    MeView,
    PasswordResetRequestView,
    PasswordResetResolveView,
    UserCreateView,
)
from .workforce_api import (
    EmployeeAvailabilityView,
    EmployeeCurrentSprintView,
    EmployeeLeaveRequestListCreateView,
    EmployeeShiftRequestListCreateView,
    EmployeeTaskDetailView,
    EmployeeTaskDropView,
    EmployeeTaskListView,
    EmployeeTaskMessageListCreateView,
    EmployeeTaskStatusUpdateView,
    EmployeeTaskSubmissionCreateView,
    EmployeeTaskTakeView,
    ManagerAvailabilityOverviewView,
    ManagerLeaveRequestListView,
    ManagerLeaveRequestReviewView,
    ManagerScheduleApproveView,
    ManagerShiftRequestDecisionView,
    ManagerShiftRequestListView,
    ManagerSprintDetailView,
    ManagerSprintListCreateView,
    ManagerSprintTaskAddView,
    ManagerSprintTaskRemoveView,
    ManagerSubstitutionDeleteView,
    ManagerSubstitutionListCreateView,
    ManagerTaskMessageListCreateView,
    ManagerTaskDetailView,
    ManagerTaskExtendView,
    ManagerTaskListCreateView,
    ManagerTeamView,
)

urlpatterns = [
    path('', ApiRootView.as_view(), name='api-root'),
    path('auth/login/', LoginView.as_view(), name='api-login'),
    path('auth/logout/', LogoutView.as_view(), name='api-logout'),
    path('auth/me/', MeView.as_view(), name='api-me'),
    path('users/', UserCreateView.as_view(), name='api-user-create'),
    path('departments/', DepartmentListView.as_view(), name='api-departments'),
    path('departments/<int:department_id>/', DepartmentDetailView.as_view(), name='api-department-detail'),
    path('departments/<int:department_id>/archive/', DepartmentArchiveView.as_view(), name='api-department-archive'),
    path('employees/', EmployeeListCreateView.as_view(), name='api-employees'),
    path('employees/<int:user_id>/', EmployeeDetailView.as_view(), name='api-employee-detail'),
    path('employees/<int:user_id>/absences/', EmployeeAbsenceView.as_view(), name='api-employee-absences'),
    path('employees/import/', EmployeeImportView.as_view(), name='api-employees-import'),
    path('employees/<int:user_id>/avatar/', EmployeeAvatarView.as_view(), name='api-employee-avatar'),
    path('employees/deactivate/', EmployeeDeactivateView.as_view(), name='api-employees-deactivate'),
    path('employees/activate/', EmployeeActivateView.as_view(), name='api-employees-activate'),
    path('password-resets/', PasswordResetRequestView.as_view(), name='api-password-reset-request'),
    path('password-resets/<int:request_id>/resolve/', PasswordResetResolveView.as_view(), name='api-password-reset-resolve'),
    path('admin/settings/', AdminSettingsView.as_view(), name='api-admin-settings'),
    path('admin/settings/history/', AdminSettingsHistoryView.as_view(), name='api-admin-settings-history'),
    path('admin/system/backups/', AdminSystemBackupCreateView.as_view(), name='api-admin-system-backups-create'),
    path(
        'admin/system/backups/<int:backup_id>/restore/',
        AdminSystemBackupRestoreView.as_view(),
        name='api-admin-system-backups-restore',
    ),
    path('admin/system/monitoring/', AdminSystemMonitoringView.as_view(), name='api-admin-system-monitoring'),
    path('manager/availability/overview/', ManagerAvailabilityOverviewView.as_view(), name='api-manager-availability-overview'),
    path('manager/availability/approve/', ManagerScheduleApproveView.as_view(), name='api-manager-availability-approve'),
    path('manager/shift-requests/', ManagerShiftRequestListView.as_view(), name='api-manager-shift-requests'),
    path('manager/shift-requests/decision/', ManagerShiftRequestDecisionView.as_view(), name='api-manager-shift-requests-decision'),
    path('manager/tasks/', ManagerTaskListCreateView.as_view(), name='api-manager-tasks'),
    path('manager/tasks/<int:task_id>/', ManagerTaskDetailView.as_view(), name='api-manager-task-detail'),
    path('manager/tasks/<int:task_id>/extend/', ManagerTaskExtendView.as_view(), name='api-manager-task-extend'),
    path('manager/tasks/<int:task_id>/messages/', ManagerTaskMessageListCreateView.as_view(), name='api-manager-task-messages'),
    path('employee/availability/', EmployeeAvailabilityView.as_view(), name='api-employee-availability'),
    path('employee/shift-requests/', EmployeeShiftRequestListCreateView.as_view(), name='api-employee-shift-requests'),
    path('employee/tasks/', EmployeeTaskListView.as_view(), name='api-employee-tasks'),
    path('employee/tasks/<int:task_id>/', EmployeeTaskDetailView.as_view(), name='api-employee-task-detail'),
    path('employee/tasks/<int:task_id>/status/', EmployeeTaskStatusUpdateView.as_view(), name='api-employee-task-status'),
    path('employee/tasks/<int:task_id>/submissions/', EmployeeTaskSubmissionCreateView.as_view(), name='api-employee-task-submission'),
    path('employee/tasks/<int:task_id>/take/', EmployeeTaskTakeView.as_view(), name='api-employee-task-take'),
    path('employee/tasks/<int:task_id>/drop/', EmployeeTaskDropView.as_view(), name='api-employee-task-drop'),
    path('employee/tasks/<int:task_id>/messages/', EmployeeTaskMessageListCreateView.as_view(), name='api-employee-task-messages'),
    path('employee/sprints/current/', EmployeeCurrentSprintView.as_view(), name='api-employee-sprint-current'),
    path('employee/leave-requests/', EmployeeLeaveRequestListCreateView.as_view(), name='api-employee-leave-requests'),
    path('manager/sprints/', ManagerSprintListCreateView.as_view(), name='api-manager-sprints'),
    path('manager/sprints/<int:sprint_id>/', ManagerSprintDetailView.as_view(), name='api-manager-sprint-detail'),
    path('manager/sprints/<int:sprint_id>/tasks/', ManagerSprintTaskAddView.as_view(), name='api-manager-sprint-tasks-add'),
    path('manager/sprints/<int:sprint_id>/tasks/<int:task_id>/', ManagerSprintTaskRemoveView.as_view(), name='api-manager-sprint-tasks-remove'),
    path('manager/leave-requests/', ManagerLeaveRequestListView.as_view(), name='api-manager-leave-requests'),
    path('manager/leave-requests/<int:lr_id>/review/', ManagerLeaveRequestReviewView.as_view(), name='api-manager-leave-request-review'),
    path('manager/substitutions/', ManagerSubstitutionListCreateView.as_view(), name='api-manager-substitutions'),
    path('manager/substitutions/<int:sub_id>/', ManagerSubstitutionDeleteView.as_view(), name='api-manager-substitution-delete'),
    path('manager/team/', ManagerTeamView.as_view(), name='api-manager-team'),
]
