from django.urls import path

from .web_views import (
    admin_dashboard,
    admin_departments,
    admin_department_detail,
    admin_payroll,
    admin_reports,
    admin_reports_export,
    admin_settings,
    admin_system,
    admin_system_backup_download,
    admin_system_logs_export,
    admin_users,
    admin_user_detail,
    profile_view,
    employee_availability,
    employee_chat,
    employee_dashboard,
    employee_profile,
    employee_requests,
    employee_schedule,
    employee_sprint,
    employee_tasks,
    employee_task_detail,
    employee_task_detail_panel,
    logout_view,
    manager_chat,
    manager_dashboard,
    manager_employee_detail,
    manager_leave_request_detail,
    manager_leave_requests,
    manager_profile,
    manager_sprint_create,
    manager_sprint_detail,
    manager_sprints,
    manager_substitutions,
    manager_tasks,
    manager_task_detail,
    manager_task_create,
    manager_task_edit,
    manager_team,
)
from .web_views_notifications import notifications_view, notifications_mark_read

urlpatterns = [
    path('logout/', logout_view, name='logout'),
    # Admin routes
    path('dashboard/admin/', admin_dashboard, name='admin-dashboard'),
    path('dashboard/admin/users/', admin_users, name='admin-users'),
    path('dashboard/admin/users/<int:user_id>/', admin_user_detail, name='admin-user-detail'),
    path('dashboard/admin/departments/', admin_departments, name='admin-departments'),
    path('dashboard/admin/departments/<int:department_id>/', admin_department_detail, name='admin-department-detail'),
    path('dashboard/admin/settings/', admin_settings, name='admin-settings'),
    path('dashboard/admin/reports/', admin_reports, name='admin-reports'),
    path('dashboard/admin/reports/export/', admin_reports_export, name='admin-reports-export'),
    path('dashboard/admin/payroll/', admin_payroll, name='admin-payroll'),
    path('dashboard/admin/system/', admin_system, name='admin-system'),
    path('dashboard/admin/system/backups/<int:backup_id>/download/', admin_system_backup_download, name='admin-system-backup-download'),
    path('dashboard/admin/system/logs/export/', admin_system_logs_export, name='admin-system-logs-export'),
    path('dashboard/profile/', profile_view, name='profile'),
    # Manager routes
    path('dashboard/manager/', manager_dashboard, name='manager-dashboard'),
    path('dashboard/manager/tasks/', manager_tasks, name='manager-tasks'),
    path('dashboard/manager/tasks/create/', manager_task_create, name='manager-task-create'),
    path('dashboard/manager/tasks/<int:task_id>/', manager_task_detail, name='manager-task-detail'),
    path('dashboard/manager/tasks/<int:task_id>/edit/', manager_task_edit, name='manager-task-edit'),
    path('dashboard/manager/sprints/', manager_sprints, name='manager-sprints'),
    path('dashboard/manager/sprints/create/', manager_sprint_create, name='manager-sprint-create'),
    path('dashboard/manager/sprints/<int:sprint_id>/', manager_sprint_detail, name='manager-sprint-detail'),
    path('dashboard/manager/team/', manager_team, name='manager-team'),
    path('dashboard/manager/team/<int:user_id>/', manager_employee_detail, name='manager-employee-detail'),
    path('dashboard/manager/leave-requests/', manager_leave_requests, name='manager-leave-requests'),
    path('dashboard/manager/leave-requests/<int:lr_id>/', manager_leave_request_detail, name='manager-leave-request-detail'),
    path('dashboard/manager/substitutions/', manager_substitutions, name='manager-substitutions'),
    path('dashboard/manager/chat/', manager_chat, name='manager-chat'),
    path('dashboard/manager/profile/', manager_profile, name='manager-profile'),
    # Employee routes
    path('dashboard/employee/', employee_dashboard, name='employee-dashboard'),
    path('dashboard/employee/tasks/', employee_tasks, name='employee-tasks'),
    path('dashboard/employee/tasks/<int:task_id>/', employee_task_detail, name='employee-task-detail'),
    path('dashboard/employee/tasks/<int:task_id>/panel/', employee_task_detail_panel, name='employee-task-detail-panel'),
    path('dashboard/employee/sprint/', employee_sprint, name='employee-sprint'),
    path('dashboard/employee/requests/', employee_requests, name='employee-requests'),
    path('dashboard/employee/chat/', employee_chat, name='employee-chat'),
    path('dashboard/employee/profile/', employee_profile, name='employee-profile'),
    # Notifications
    path('dashboard/notifications/', notifications_view, name='notifications'),
    path('dashboard/notifications/mark-read/', notifications_mark_read, name='notifications-mark-read'),
    # Legacy redirects (kept for any bookmarked links)
    path('dashboard/employee/schedule/', employee_schedule, name='employee-schedule'),
    path('dashboard/employee/availability/', employee_availability, name='employee-availability'),
]
