# Generated by Django 5.2.10 on 2026-02-01 10:14

import accounts.models
import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_employee_department_change_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField(default=datetime.time(7, 0))),
                ('work_end', models.TimeField(default=datetime.time(23, 0))),
                ('work_days', models.CharField(choices=[('daily', 'Ежедневно'), ('weekdays', 'Пн–Пт'), ('week6', 'Пн–Сб')], default='daily', max_length=20)),
                ('ot_threshold', models.PositiveIntegerField(default=12)),
                ('ot_coeff', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=4)),
                ('shift_templates', models.JSONField(blank=True, default=accounts.models._default_shift_templates)),
                ('allow_custom_shifts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_global_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettingsChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
