# Generated by Django 5.2.10 on 2026-04-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_data_integrity_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='backup_retention_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='task_submission_max_file_size_mb',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='task_submission_max_files',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
