# Generated by Django 5.2.10 on 2026-04-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_globalsettings_backup_retention_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='allow_password_reset_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='global_announcement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='platform_name',
            field=models.CharField(default='Conector Shift', max_length=100),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='support_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
