# Generated by Django 5.2.10 on 2026-04-19 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_map_task_statuses(apps, schema_editor):
    DepartmentTask = apps.get_model('accounts', 'DepartmentTask')
    DepartmentTask.objects.filter(status='todo').update(status='awaiting_confirmation')
    DepartmentTask.objects.filter(status='done').update(status='completed')


def backwards_map_task_statuses(apps, schema_editor):
    DepartmentTask = apps.get_model('accounts', 'DepartmentTask')
    DepartmentTask.objects.filter(status='awaiting_confirmation').update(status='todo')
    DepartmentTask.objects.filter(status='completed').update(status='done')
    DepartmentTask.objects.filter(status='confirmed').update(status='in_progress')
    DepartmentTask.objects.filter(status='conflict').update(status='in_progress')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_globalsettings_allow_password_reset_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttask',
            name='status',
            field=models.CharField(choices=[('awaiting_confirmation', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('conflict', 'Конфликт'), ('in_progress', 'В процессе'), ('completed', 'Выполнено')], default='awaiting_confirmation', max_length=30),
        ),
        migrations.CreateModel(
            name='EmployeeAvailabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('override_type', models.CharField(choices=[('unavailable', 'Недоступен'), ('partial', 'Частичная доступность'), ('available', 'Я доступен весь день'), ('vacation', 'Отпуск'), ('sick', 'Больничный')], default='unavailable', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_employee_availability_override_date'), models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='chk_availability_override_time_order')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBaseAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('mode', models.CharField(choices=[('off', 'Недоступен'), ('fixed', 'Фиксированные часы'), ('flex', 'Свободный график')], default='off', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_availability_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('user', 'weekday'), name='unique_employee_base_availability_weekday'), models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='chk_base_availability_time_order')],
            },
        ),
        migrations.CreateModel(
            name='EmployeePlannedLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('target_mode', models.CharField(choices=[('none', 'Без плановой загрузки'), ('hours', 'Часы в неделю'), ('days', 'Дни в неделю')], default='none', max_length=20)),
                ('target_value', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_loads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='unique_employee_planned_load_week')],
            },
        ),
        migrations.RunPython(forwards_map_task_statuses, backwards_map_task_statuses),
    ]
