# Generated by Django 5.2.10 on 2026-04-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_leaverequest_sprint_substitution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
    ]
