# Generated by Django 5.2.10 on 2026-05-02 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_leaverequest_cancelled_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('vacation', 'Отпуск'), ('sick', 'Больничный'), ('substitution', 'Замещение'), ('manual', 'Перераспределение')], default='manual', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_reassignments', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reassignments', to='accounts.leaverequest')),
                ('new_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_gained', to=settings.AUTH_USER_MODEL)),
                ('previous_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_lost', to=settings.AUTH_USER_MODEL)),
                ('substitution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reassignments', to='accounts.substitution')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='accounts.departmenttask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'created_at'], name='idx_task_reassign_task')],
            },
        ),
    ]
