# Generated by Django 5.2.10 on 2026-05-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_taskreassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttask',
            name='priority',
            field=models.CharField(choices=[('critical', 'Критический'), ('high', 'Высокий'), ('mid', 'Средний'), ('low', 'Низкий')], default='mid', max_length=10),
        ),
    ]
