# Generated by Django 5.2.10 on 2026-05-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_departmenttask_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
    ]
