# Generated by Django 5.2.10 on 2026-05-05 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_leaverequest_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttask',
            name='manager_review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departmenttask',
            name='refusal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task_taken', 'Сотрудник взял задачу'), ('task_dropped', 'Сотрудник отказался от задачи'), ('task_on_review', 'Задача отправлена на проверку'), ('task_returned', 'Задача возвращена на доработку'), ('task_completed', 'Задача принята'), ('task_assigned', 'Назначена новая задача'), ('task_reassigned', 'Задача переназначена'), ('leave_request_new', 'Новая заявка на отпуск/больничный'), ('leave_request_decision', 'Решение по заявке'), ('substitution_assigned', 'Назначена замена')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emitted_notifications', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.leaverequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.departmenttask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='idx_notif_recipient_read'), models.Index(fields=['recipient', '-created_at'], name='idx_notif_recipient_date')],
            },
        ),
        migrations.CreateModel(
            name='TaskStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status_changes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='accounts.departmenttask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='idx_task_history_task')],
            },
        ),
    ]
