# Generated by Django 5.2.10 on 2026-05-05 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_departmenttask_manager_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='substitute_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_as_substitute', to=settings.AUTH_USER_MODEL),
        ),
    ]
